### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by aatishnn** [foss-np/anubad#3]
While trying to `make` project, I get the following errors:

```
./app.py
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2158, in _find_spec
AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./app.py", line 5, in <module>
    from gi.repository import Keybinder
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 53, in find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name Keybinder, introspection typelib not found
```

**Comment by rhoit** [comment]
@aatishnn this is well know error! you have to install `libkeybinder` as stated in requirements.
this is only required for external keybinding and plug-ins, so I have removed it in 0.96-1 fix.

**Comment by aatishnn** [comment]
Thanks, new one worked.
